### PR TITLE
LPS-91408 fix wcm refresh

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-91408

This probably needs to be cleaned up, but it is working.

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by ryannealeigh** [comment]
ci:stop

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
Currently reviewing.

**Comment by SpencerWoo** [comment]
forwarded https://github.com/gregory-bretall/liferay-portal/pull/170

**Pull request closed without merging**
