### PR TITLE
LPS-94895 use escapeJS instead of regular escape

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-94895

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
forwarded https://github.com/jonathanmccann/liferay-portal/pull/1807

**Pull request closed without merging**
