### PR TITLE
LPS-92188 remove slash in JournalArticle urlTitle

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-92188

Tomcat does not allow encoded slashes in the url due to security vulnerability. Unencoded slashes also don't work because it breaks the friendlyURL. Here we want to remove any slashes from the URL title when the journal article is being created so that the 400 error doesn't occur.

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
@ryannealeigh1 can you update the first comment https://github.com/SpencerWoo/liferay-portal/pull/56#issue-263781054 and provide a detailed description of the fix?  thanks

**Comment by SpencerWoo** [comment]
Just started reviewing

**Comment by SpencerWoo** [comment]
@ryannealeigh1 
I'm unable to reproduce the issue without your commit (or reverting your commit on this branch) -- I get the XSS message.

Reopen and lmk if it's still reproducible and I have something wrong

**Pull request closed without merging**
