### PR TITLE
LPS-88743 Circularly referenced web-content throws exception on import

### PR DESCRIPTION
**Pull request by ricky-pan**
See conversation here: https://github.com/SpencerWoo/liferay-portal-ee/pull/68

Bug cannot be fully reproduced on master because of https://issues.liferay.com/browse/LPS-90401. However, based on the logic of the code, the issue present in 7.1 should then become reproducible after fixing LPS-90401.

### CODE REVIEW

**Comment by ricky-pan** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
hey @ricky-pan looks good to me and glad we cna resolve this on Master as well.

Unfortunately however I don't think I can forward this because we're blocked by LPS-90401.  

The CS can open another LPP for the LPS-90401 blocking issue.  Additionally if it's a high priority I can try to forward the 71x fix you had but if it isn't high severity we should do the normal correct process.  Hope that makes sense

**Comment by SpencerWoo** [comment]
Actually I want to try one thing first

**Comment by SpencerWoo** [comment]
Closing as per https://github.com/SpencerWoo/liferay-portal/pull/47#issuecomment-469898456

**Comment by SpencerWoo** [comment]
forwarded https://github.com/jonathanmccann/liferay-portal/pull/1782

**Pull request closed without merging**
