### PR TITLE
LPS-88984 Prevent youtube portlet iframe from overflowing portlet boundaries

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-88984

Resize youtube portlet iframe whenever portlet is added to page, dragged to new location, or window is resized

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
@jrao 
Closing -- looks like there's formatting issues https://github.com/SpencerWoo/liferay-portal/pull/42#issuecomment-461926864

Additionally
(1) Link the LPS or relevant ticket every time you PR.

(2) Transition the LPS to "In Review" -- involves changing the assignee and making jira aware of the PR link.  In this case I believe there's a button on the LPS (lmk if it's unclear) -- and you'd change the assignee to the reviewer (me) and link the PR

**Comment by jrao** [comment]
sent https://github.com/SpencerWoo/liferay-portal/pull/43

**Pull request closed without merging**
