### PR TITLE
LPS-91408 remove portlet refresh

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-91408

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
@ryannealeigh1 
You're right the refresh looks intentional.  Do you know why we were refreshing?  That would make this either a regression or the refresh is no longer expected behavior and outdated

I'll fully review once the test finishes / later

**Comment by ryannealeigh** [comment]
@SpencerWoo I looked at [LPS-66304](https://issues.liferay.com/browse/LPS-66304) and it appears that they wanted to refresh for usability purposes...not quite sure and there's not much more detail.

**Comment by ryannealeigh** [comment]
@SpencerWoo I just tested this and found out that the refresh refreshes the add modal / "plus button pattern" to quote the original ticket and displays the favorites in that list. Basically web content structures that are marked as favorites do not show up as favorites until the portlet is refreshed or the folder is changed.

**Comment by SpencerWoo** [comment]
thanks for looking into the background, very good to know

> Basically web content structures that are marked as favorites do not show up as favorites until the portlet is refreshed or the folder is changed.

It seems this use case is still valid and hasn't changed -- we still want the favorites to update without additional user interaction

I'll close this as the ideal fix should resolve LPS-91408 and not regress LPS-66304 behavior.

**Pull request closed without merging**
