### PR TITLE
LPS-99243 Remove <h1> tag from all themes

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-99243

I simply replaced the `<h1>` tags with either a `<span>` or `<div>`, but I'm not positive that won't affect some styling. From first glance, it looks as though the `<h1>` tags were not used as the style selector, and only the class="??" was used, which leads me to believe that the styling would not be affected by the change. Not sure how to test fully though.

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
@ryannealeigh I looked at PTR-1053

Can you describe why `<span>` and `<div>` are valid here for accessibility?  Additionally if we're not planning to backport this we can change the LPS

**Comment by ryannealeigh** [comment]
@SpencerWoo Daniel Sanz talks about `<span>` and `<div>` here: https://issues.liferay.com/browse/PTR-1053?focusedCommentId=1901219&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1901219.

I did overlook one comment however: https://issues.liferay.com/browse/PTR-1053?focusedCommentId=1902260&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1902260

It appears that I should add role="heading" aria-level="1" to each of these tags as well. I'll send another commit.

I closed the BPR on the LPS.

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
@ryannealeigh 

I think https://issues.liferay.com/browse/PTR-1053?focusedCommentId=1916084&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1916084 should also be applied

Let me know if you interpret it differently, I'll close this.

other general comments : 
(1) I was looking for the specification that details this is justified but I believe I found the reference https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA12 

(2) I think we can make this a Story because of the content and to ensure it isn't mistakenly backported.

(3) Regarding testing, one way is to make sure a screen reader interprets the page properly / the same as with h1.  I presume it functions the same as it looks good to me

**Comment by ryannealeigh** [comment]
@SpencerWoo 
Do you think that is to remove the `<h1>` entirely?

I didn't think that at first, but looking again, it seems more like it. I thought it should stay at first as there was a language key in the `<h1>`, but the class is `hide-accessible` so does that mean it is hidden anyway and was only needed for accessibility in the first place?

**Pull request closed without merging**
