### PR TITLE
LPS-92186 escape JournalArticle title

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-92186
Resubmit of https://github.com/SpencerWoo/liferay-portal/pull/53

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
Just started reviewing

**Comment by SpencerWoo** [comment]
@ryannealeigh1 is there a reason we're doing escapeAttribute() and not escape()?

other than that looks simple and I'm okay to forward

**Comment by SpencerWoo** [comment]
I'll close this.  Resend with escape or lmk why we're using escapeAttribute

**Comment by ryannealeigh** [comment]
@SpencerWoo I'm using escapeAttribute based on precedence. I found other instances in source where escapeAttribute() was used in this exact situation.

**Comment by ryannealeigh** [comment]
https://github.com/liferay/liferay-portal/blob/fe24952a07c638e866715fcf2666d0c64bb12a04/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/view_entry.jsp#L76

**Comment by ryannealeigh** [comment]
https://github.com/liferay/liferay-portal/blob/fcc152165b8cf34cb595e5a712c2ea07a8498c3c/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/asset/full_content.jsp#L33

**Comment by ryannealeigh** [comment]
There are two other examples.

**Comment by SpencerWoo** [comment]
cool, sounds good

forwarded https://github.com/jonathanmccann/liferay-portal/pull/1787

**Pull request closed without merging**
