### PR TITLE
LPS-96947 add 1px padding to bottom

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-96947

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
low priority.  on hold for now.  lmk if that's not the case

**Comment by SpencerWoo** [comment]
I think I'll want to change this as the Search Bar looks correct with 0.  Also Suggestions and Site Facet looks properly empty with 0.

I'll look into this more on Monday.

**Comment by SpencerWoo** [comment]
1px looks good for the Type widget (as described in the LPS), however I think Search Bar, Suggestions, and Site Facet look more correct as-is (0).

[https://imgur.com/3y24f4d](url)

In that screenshot it shows that each widget looks differently, thus changing 0 to 1px isn't good for some, and fixes others.  Ideally they'd all be the same so they would all appear properly with either 1px or 0.  I held onto this as I was planning on modifying the solution however given the priority I don't foresee working on this soon so I'll close this.

**Pull request closed without merging**
