### PR TITLE
LPP-26782 Route /favicon.ico request through a servlet

### PR DESCRIPTION
**Pull request by brunobasto**
@izaera, can you take a look and see if we can do it better?

I don't like that we are referencing a module Servlet path from portal-web/docroot/WEB-INF/urlrewrite.xml

Thanks!

### CODE REVIEW

**Comment by SpencerWoo** [comment]
Thanks Bruno!  I'm building to test this fix now.

@gregory-bretall Have you had a chance to test this?

**Comment by gregory-bretall** [comment]
I haven't but I can test it now if you want, I just had to redeploy master because my build wasn't working.

**Comment by gregory-bretall** [comment]
So I tested this in master and no longer got the WARN this is made to fix when logging in with IE11, but I am still getting this warning: 17:26:49,007 WARN  [http-nio-8080-exec-2][code_jsp:172] {code="404", msg="ProxyServlet: /o/adaptive-media-image-web/picturefill.js", uri=/o/adaptive-media-image-web/picturefill.js}.  I'm fairly certain this is unrelated though.

**Comment by SpencerWoo** [comment]
Thanks for testing Greg.  That warning should be fixed by https://issues.liferay.com/browse/LPS-74076.

I'm still in the process of getting Master running to test this.  I'll look at the consistency of the favicon issue.

**Comment by SpencerWoo** [comment]
I've tested and got the same results as Greg and the same results you've listed in your email.  I've tried other things but to no avail -- this looks good to resolve the warn error issue. 

When we decide to push this forward I'll tell CS to inform the customer on the favicon IE 11 history.pushState issue and hopefully they understand why it isn't SPA fixable with the youtube.com and react example.

**Pull request closed without merging**
