### PR TITLE
LPS-89030 Updated tooltip language key

### PR DESCRIPTION
**Pull request by ryannealeigh**
Updated tooltip language key and ran gradlew buildLang.

https://issues.liferay.com/browse/LPS-89030

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test

**Comment by SpencerWoo** [comment]
@ryannealeigh1 
https://github.com/SpencerWoo/liferay-portal/pull/39/commits/110c53b9fd0fe7e851d23cb25585d74734fb353f#diff-31a2e8213d159dcec1a2fe8563d24d0aR38 -- is that an official description from somewhere?

Also it looks like originAI isn't configured.  I'm running tests here https://github.com/SpencerWoo/liferay-portal/pull/40#issuecomment-461562084.  I guess open the QA ticket if the instructions say so / ask the others how they set it up.

**Comment by ryannealeigh** [comment]
I grabbed the description from here: https://dev.liferay.com/discover/portal/-/knowledge_base/6-2/managing-user-segments although that is 6.2 so maybe it isn't correct.

**Comment by SpencerWoo** [comment]
forwarded https://github.com/jonathanmccann/liferay-portal/pull/1771

**Pull request closed without merging**
