### PR TITLE
LPS-99791 Reindex User when indexed fields are updated

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-99791

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
@ryannealeigh update the LPS with steps to reproduce so it's clear when that this fixes the bug issue

**Comment by ryannealeigh** [comment]
@SpencerWoo I updated the LPS with the reproduction steps for the emailAddress case only.

The same idea would apply to many different fields other than just emailAddress though, and this pull contains the fix for all of the fields that appear to be indexable by my obervations in https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/usersadmin/util/UserIndexer.java#L250-L285

**Comment by SpencerWoo** [comment]
some of these probably shouldn't be indexed but forwarded https://github.com/jonathanmccann/liferay-portal/pull/1823

**Pull request closed without merging**
