### PR TITLE
LPS-87985 Form date field ignores locale-specific formatting

### PR DESCRIPTION
**Pull request by ricky-pan**
Relevant tickets: 
https://issues.liferay.com/browse/LPS-87985
https://issues.liferay.com/browse/LPP-32222
https://issues.liferay.com/browse/LPP-31603 (regression here, code [here](https://github.com/brianchandotcom/liferay-portal/pull/62909/files))

Issues: 
1) Liferay form date-formats only support 3 orderings of mm/dd/yy, and the characters separating each field must be '/'s. 
2) It also doesn't allow for users to deploy their own date-field format overrides.

Solution: 
1) In `top_js.jspf`, I edited how Liferay returns a DateFormat object given a locale. Previously, there were only 3, but using Java's DateFormats, there are 100+. The JS methods for parsing DateFormats uses strftime, which is in PHP, so I had to manually parse and process the dateformats for characters so that the front end can use it.
2) I added a check for custom date formats in `date_field.js`, which are loaded upon page loading, so that the custom format would override the default if it is present. It makes use of [YUI's standard date formats](https://yuilibrary.com/yui/docs/datatype/index.html#addDateFormat).

### CODE REVIEW

**Comment by ricky-pan** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
@ricky-pan Overall this looks good to forward though I'd like to talk to you to understand some things

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
@ricky-pan see SF test.  I'll close this one, please fix and resend -- thanks!

**Pull request closed without merging**
